config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions', omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get 'users/profile' => 'users/registrations#profile'
  end

  resources :users, :only => [:index, :show]
  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :microposts, :only => [:new, :create, :destroy, :show]
  resources :relationships, :only => [:create, :destroy]
  root 'static_pages#home'
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :content, length: { maximum: 140 }
  validate  :picture_size

 private

   # アップロードされた画像のサイズをバリデーションする
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :authenticate_user!, only:[:create, :destroy]

  def new
    @micropost = Micropost.new
  end

  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "作成されました!"
      redirect_to users_profile_url
    else
      render 'static_pages/home'
    end
  end

  def show
    @micropost = Micropost.find_by(id: params[:id])
  end

  def destroy
    @micropost = current_user.microposts.find_by(id: params[:id])
    @micropost.destroy
    flash[:success] = "削除されました！"
    redirect_to request.referrer || root_url
  end

  private

  def micropost_params
    params.require(:micropost).permit(:picture, :content)
  end
end

app/views/microposts/_microposts.html.erb
<div class="content-picture">
  <div class="picture">
    <%= link_to image_tag(microposts.picture.thumb.url), micropost_path(microposts) %>
  </div>
</div>

app/views/microposts/new.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'devise/shared/error_messages', resource: f.object %>
  <span class="picture">
     <%= f.file_field :picture, accept: 'image/jpeg,image/png' %>
     <%= f.text_area :content %>
  </span>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/microposts/show.html.erb
<div class="micropost-show">
  <%= image_tag(@micropost.picture.url) %>
</div>
<div class="micropost-content">
  <p>
    <%= link_to "@#{@micropost.user.username}", user_path(@micropost.user) %>
    <%= @micropost.content%>
  </p>
  <span class="timestamp">
    Posted <%= time_ago_in_words(@micropost.created_at) if @micropost.created_at %> ago.
    <% if @micropost.user == current_user %>
      <%= link_to "削除", micropost_path, method: :delete,
                                      data: { confirm: "You sure?" } %>
    <% end %>
  </span>
</div>