config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions', omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get 'users/profile' => 'users/registrations#profile'
  end

  resources :users, :only => [:index, :show]
  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :microposts, :only => [:new, :create, :destroy, :show]
  resources :relationships, :only => [:create, :destroy]
  root 'static_pages#home'
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <li><%= link_to "写真アップロード画面", new_micropost_path %></li>
  <p>サブ課題　by Masashi Sumiishi</p>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar">
  <div class="container">
    <nav class="navi">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
        <% if current_user.present? %>
          <li><%= link_to "My page", users_profile_path %></li>
          <li><%= link_to "ユーザー一覧", users_path %></li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>